name: Task
description: Create a new specific piece of work.
title: "[Task]: "
labels: []
projects: ["databeacon/17"]
type: task
body:
  - type: textarea
    id: what-needs-to-be-done
    attributes:
      label: What needs to be done?
      description: What is the required change?
      value: "Description of the required task"
    validations:
      required: true
