name: Feature
description: A request, idea or new functionality.
title: "[Feature]: "
labels: []
projects: ["tango5-aero/1"]
type: feature
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What needs to be done?
      description: What is the required change?
      value: "Description of the idea or new functionality"
    validations:
      required: true
